//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class _Default {
    
    /// <summary>
    /// rptHeadlines control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Repeater rptHeadlines;
    
    /// <summary>
    /// WorldNews control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Khabardaan.Web.UI.UserControls.NewsList WorldNews;
    
    /// <summary>
    /// BusinessNews control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Khabardaan.Web.UI.UserControls.NewsList BusinessNews;
    
    /// <summary>
    /// TechnologyNews control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Khabardaan.Web.UI.UserControls.NewsList TechnologyNews;
    
    /// <summary>
    /// EntertainmentNews control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Khabardaan.Web.UI.UserControls.NewsList EntertainmentNews;
    
    /// <summary>
    /// SportsNews control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Khabardaan.Web.UI.UserControls.NewsList SportsNews;
    
    /// <summary>
    /// ScienceNews control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Khabardaan.Web.UI.UserControls.NewsList ScienceNews;
    
    /// <summary>
    /// HealthNews control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Khabardaan.Web.UI.UserControls.NewsList HealthNews;
}
