<?xml version="1.0" encoding="utf-8"?><Database Name="Dic" Class="DictionariesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=RoboNewser;Persist Security Info=True;User ID=sa;MultipleActiveResultSets=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RoboNewserConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.EF" Member="EFs">
    <Type Name="EF">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Word" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Meaning" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EA" Member="EAs">
    <Type Name="EA">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Word" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Meaning" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EE" Member="EEs">
    <Type Name="EE">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Word" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Meaning" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EG" Member="EGs">
    <Type Name="EG">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Word" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Meaning" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EI" Member="EIs">
    <Type Name="EI">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Word" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Meaning" Type="System.String" DbType="VarChar(2500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ES" Member="ES">
    <Type Name="ES">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Word" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Meaning" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SearchedWords" Member="SearchedWords">
    <Type Name="SearchedWords">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Word" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Dic" Type="System.String" DbType="Char(3)" CanBeNull="true" />
      <Column Name="IP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>