<?xml version="1.0" encoding="utf-8"?><Database Name="RoboNewser" Class="EventsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=RoboNewser;Persist Security Info=True;User ID=sa;MultipleActiveResultSets=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RoboNewserConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Events" Member="Events">
    <Type Name="Events">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Date" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Event" Member="Event1" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="EYear" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EMonth" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EDay" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>