#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoboNewser.Code.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RoboNewserDB")]
	public partial class KeywordsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEntityKeywords(EntityKeywords instance);
    partial void UpdateEntityKeywords(EntityKeywords instance);
    partial void DeleteEntityKeywords(EntityKeywords instance);
    partial void InsertSpecialKeywords(SpecialKeywords instance);
    partial void UpdateSpecialKeywords(SpecialKeywords instance);
    partial void DeleteSpecialKeywords(SpecialKeywords instance);
    partial void InsertGarbageWords(GarbageWords instance);
    partial void UpdateGarbageWords(GarbageWords instance);
    partial void DeleteGarbageWords(GarbageWords instance);
    partial void InsertKeywords(Keywords instance);
    partial void UpdateKeywords(Keywords instance);
    partial void DeleteKeywords(Keywords instance);
    #endregion
		
		public KeywordsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["RoboNewserConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public KeywordsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KeywordsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KeywordsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KeywordsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<vTitleKeywords> vTitleKeywords
		{
			get
			{
				return this.GetTable<vTitleKeywords>();
			}
		}
		
		public System.Data.Linq.Table<vEntityKeywords> vEntityKeywords
		{
			get
			{
				return this.GetTable<vEntityKeywords>();
			}
		}
		
		public System.Data.Linq.Table<EntityKeywords> EntityKeywords
		{
			get
			{
				return this.GetTable<EntityKeywords>();
			}
		}
		
		public System.Data.Linq.Table<SpecialKeywords> SpecialKeywords
		{
			get
			{
				return this.GetTable<SpecialKeywords>();
			}
		}
		
		public System.Data.Linq.Table<vSpecialKeywords> vSpecialKeywords
		{
			get
			{
				return this.GetTable<vSpecialKeywords>();
			}
		}
		
		public System.Data.Linq.Table<vKeywords> vKeywords
		{
			get
			{
				return this.GetTable<vKeywords>();
			}
		}
		
		public System.Data.Linq.Table<vUsedKeywords> vUsedKeywords
		{
			get
			{
				return this.GetTable<vUsedKeywords>();
			}
		}
		
		public System.Data.Linq.Table<GarbageWords> GarbageWords
		{
			get
			{
				return this.GetTable<GarbageWords>();
			}
		}
		
		public System.Data.Linq.Table<vGarbageWords> vGarbageWords
		{
			get
			{
				return this.GetTable<vGarbageWords>();
			}
		}
		
		public System.Data.Linq.Table<NewsKeywords> NewsKeywords
		{
			get
			{
				return this.GetTable<NewsKeywords>();
			}
		}
		
		public System.Data.Linq.Table<vNewsKeywords> vNewsKeywords
		{
			get
			{
				return this.GetTable<vNewsKeywords>();
			}
		}
		
		public System.Data.Linq.Table<vImportantKeyword> vImportantKeywords
		{
			get
			{
				return this.GetTable<vImportantKeyword>();
			}
		}
		
		public System.Data.Linq.Table<vKeywordRoles> vKeywordRoles
		{
			get
			{
				return this.GetTable<vKeywordRoles>();
			}
		}
		
		public System.Data.Linq.Table<Keywords> Keywords
		{
			get
			{
				return this.GetTable<Keywords>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAddtoGrabagge")]
		public int spAddtoGrabagge([global::System.Data.Linq.Mapping.ParameterAttribute(Name="KeywordCode", DbType="Int")] System.Nullable<int> keywordCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), keywordCode);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vTitleKeywords")]
	public partial class vTitleKeywords
	{
		
		private string _Title;
		
		public vTitleKeywords()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(101)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vEntityKeywords")]
	public partial class vEntityKeywords
	{
		
		private int _Code;
		
		private string _Keyword;
		
		private string _Name;
		
		public vEntityKeywords()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keyword", DbType="NVarChar(100)")]
		public string Keyword
		{
			get
			{
				return this._Keyword;
			}
			set
			{
				if ((this._Keyword != value))
				{
					this._Keyword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(500)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EntityKeywords")]
	public partial class EntityKeywords : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private int _KeywordCode;
		
		private int _HCEntityTypeCode;
		
		private int _EntityCode;
		
		private System.Nullable<bool> _Deleted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnKeywordCodeChanging(int value);
    partial void OnKeywordCodeChanged();
    partial void OnHCEntityTypeCodeChanging(int value);
    partial void OnHCEntityTypeCodeChanged();
    partial void OnEntityCodeChanging(int value);
    partial void OnEntityCodeChanged();
    partial void OnDeletedChanging(System.Nullable<bool> value);
    partial void OnDeletedChanged();
    #endregion
		
		public EntityKeywords()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeywordCode", DbType="Int NOT NULL")]
		public int KeywordCode
		{
			get
			{
				return this._KeywordCode;
			}
			set
			{
				if ((this._KeywordCode != value))
				{
					this.OnKeywordCodeChanging(value);
					this.SendPropertyChanging();
					this._KeywordCode = value;
					this.SendPropertyChanged("KeywordCode");
					this.OnKeywordCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCEntityTypeCode", DbType="Int NOT NULL")]
		public int HCEntityTypeCode
		{
			get
			{
				return this._HCEntityTypeCode;
			}
			set
			{
				if ((this._HCEntityTypeCode != value))
				{
					this.OnHCEntityTypeCodeChanging(value);
					this.SendPropertyChanging();
					this._HCEntityTypeCode = value;
					this.SendPropertyChanged("HCEntityTypeCode");
					this.OnHCEntityTypeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntityCode", DbType="Int NOT NULL")]
		public int EntityCode
		{
			get
			{
				return this._EntityCode;
			}
			set
			{
				if ((this._EntityCode != value))
				{
					this.OnEntityCodeChanging(value);
					this.SendPropertyChanging();
					this._EntityCode = value;
					this.SendPropertyChanged("EntityCode");
					this.OnEntityCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Bit")]
		public System.Nullable<bool> Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this.OnDeletedChanging(value);
					this.SendPropertyChanging();
					this._Deleted = value;
					this.SendPropertyChanged("Deleted");
					this.OnDeletedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SpecialKeywords")]
	public partial class SpecialKeywords : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private System.Nullable<int> _KeywordCode;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnKeywordCodeChanging(System.Nullable<int> value);
    partial void OnKeywordCodeChanged();
    #endregion
		
		public SpecialKeywords()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeywordCode", DbType="Int")]
		public System.Nullable<int> KeywordCode
		{
			get
			{
				return this._KeywordCode;
			}
			set
			{
				if ((this._KeywordCode != value))
				{
					this.OnKeywordCodeChanging(value);
					this.SendPropertyChanging();
					this._KeywordCode = value;
					this.SendPropertyChanged("KeywordCode");
					this.OnKeywordCodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vSpecialKeywords")]
	public partial class vSpecialKeywords
	{
		
		private int _Code;
		
		private System.Nullable<int> _KeywordCode;
		
		private string _Name;
		
		public vSpecialKeywords()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeywordCode", DbType="Int")]
		public System.Nullable<int> KeywordCode
		{
			get
			{
				return this._KeywordCode;
			}
			set
			{
				if ((this._KeywordCode != value))
				{
					this._KeywordCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vKeywords")]
	public partial class vKeywords
	{
		
		private int _Code;
		
		private string _Name;
		
		private string _EngName;
		
		private string _Description;
		
		public vKeywords()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EngName", DbType="NVarChar(50)")]
		public string EngName
		{
			get
			{
				return this._EngName;
			}
			set
			{
				if ((this._EngName != value))
				{
					this._EngName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vUsedKeywords")]
	public partial class vUsedKeywords
	{
		
		private int _Code;
		
		private string _Name;
		
		private string _EngName;
		
		private string _Description;
		
		public vUsedKeywords()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EngName", DbType="NVarChar(50)")]
		public string EngName
		{
			get
			{
				return this._EngName;
			}
			set
			{
				if ((this._EngName != value))
				{
					this._EngName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GarbageWords")]
	public partial class GarbageWords : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private string _Word;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnWordChanging(string value);
    partial void OnWordChanged();
    #endregion
		
		public GarbageWords()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Word", DbType="NVarChar(100)")]
		public string Word
		{
			get
			{
				return this._Word;
			}
			set
			{
				if ((this._Word != value))
				{
					this.OnWordChanging(value);
					this.SendPropertyChanging();
					this._Word = value;
					this.SendPropertyChanged("Word");
					this.OnWordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vGarbageWords")]
	public partial class vGarbageWords
	{
		
		private int _Code;
		
		private string _Word;
		
		public vGarbageWords()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Word", DbType="NVarChar(100)")]
		public string Word
		{
			get
			{
				return this._Word;
			}
			set
			{
				if ((this._Word != value))
				{
					this._Word = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vNewsKeywords")]
	public partial class NewsKeywords
	{
		
		private int _Code;
		
		private int _EntityCode;
		
		private string _Name;
		
		private int _KeywordCode;
		
		public NewsKeywords()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntityCode", DbType="Int NOT NULL")]
		public int EntityCode
		{
			get
			{
				return this._EntityCode;
			}
			set
			{
				if ((this._EntityCode != value))
				{
					this._EntityCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeywordCode", DbType="Int NOT NULL")]
		public int KeywordCode
		{
			get
			{
				return this._KeywordCode;
			}
			set
			{
				if ((this._KeywordCode != value))
				{
					this._KeywordCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vNewsKeywords")]
	public partial class vNewsKeywords
	{
		
		private int _Code;
		
		private int _EntityCode;
		
		private string _Name;
		
		private int _KeywordCode;
		
		public vNewsKeywords()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntityCode", DbType="Int NOT NULL")]
		public int EntityCode
		{
			get
			{
				return this._EntityCode;
			}
			set
			{
				if ((this._EntityCode != value))
				{
					this._EntityCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeywordCode", DbType="Int NOT NULL")]
		public int KeywordCode
		{
			get
			{
				return this._KeywordCode;
			}
			set
			{
				if ((this._KeywordCode != value))
				{
					this._KeywordCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vImportantKeywords")]
	public partial class vImportantKeyword
	{
		
		private string _Keyword;
		
		private int _KeywordCode;
		
		private System.Nullable<int> _KeywordCount;
		
		public vImportantKeyword()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keyword", DbType="NVarChar(100)")]
		public string Keyword
		{
			get
			{
				return this._Keyword;
			}
			set
			{
				if ((this._Keyword != value))
				{
					this._Keyword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeywordCode", DbType="Int NOT NULL")]
		public int KeywordCode
		{
			get
			{
				return this._KeywordCode;
			}
			set
			{
				if ((this._KeywordCode != value))
				{
					this._KeywordCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeywordCount", DbType="Int")]
		public System.Nullable<int> KeywordCount
		{
			get
			{
				return this._KeywordCount;
			}
			set
			{
				if ((this._KeywordCount != value))
				{
					this._KeywordCount = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vKeywordRoles")]
	public partial class vKeywordRoles
	{
		
		private int _Code;
		
		private string _Name;
		
		private string _Description;
		
		private System.Nullable<int> _HCKeywordTypeCode;
		
		private string _ImgUrl;
		
		private string _Role;
		
		private string _ImgPath;
		
		private string _KRole;
		
		public vKeywordRoles()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCKeywordTypeCode", DbType="Int")]
		public System.Nullable<int> HCKeywordTypeCode
		{
			get
			{
				return this._HCKeywordTypeCode;
			}
			set
			{
				if ((this._HCKeywordTypeCode != value))
				{
					this._HCKeywordTypeCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImgUrl", DbType="NVarChar(500)")]
		public string ImgUrl
		{
			get
			{
				return this._ImgUrl;
			}
			set
			{
				if ((this._ImgUrl != value))
				{
					this._ImgUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="NVarChar(4000)")]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this._Role = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImgPath", DbType="NVarChar(50)")]
		public string ImgPath
		{
			get
			{
				return this._ImgPath;
			}
			set
			{
				if ((this._ImgPath != value))
				{
					this._ImgPath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KRole", DbType="NVarChar(300)")]
		public string KRole
		{
			get
			{
				return this._KRole;
			}
			set
			{
				if ((this._KRole != value))
				{
					this._KRole = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Keywords")]
	public partial class Keywords : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private string _Name;
		
		private string _EngName;
		
		private string _Description;
		
		private System.Nullable<int> _HCKeywordTypeCode;
		
		private System.Nullable<bool> _HasPic;
		
		private string _ImgUrl;
		
		private string _Role;
		
		private string _ImgPath;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnEngNameChanging(string value);
    partial void OnEngNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnHCKeywordTypeCodeChanging(System.Nullable<int> value);
    partial void OnHCKeywordTypeCodeChanged();
    partial void OnHasPicChanging(System.Nullable<bool> value);
    partial void OnHasPicChanged();
    partial void OnImgUrlChanging(string value);
    partial void OnImgUrlChanged();
    partial void OnRoleChanging(string value);
    partial void OnRoleChanged();
    partial void OnImgPathChanging(string value);
    partial void OnImgPathChanged();
    #endregion
		
		public Keywords()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EngName", DbType="NVarChar(50)")]
		public string EngName
		{
			get
			{
				return this._EngName;
			}
			set
			{
				if ((this._EngName != value))
				{
					this.OnEngNameChanging(value);
					this.SendPropertyChanging();
					this._EngName = value;
					this.SendPropertyChanged("EngName");
					this.OnEngNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCKeywordTypeCode", DbType="Int")]
		public System.Nullable<int> HCKeywordTypeCode
		{
			get
			{
				return this._HCKeywordTypeCode;
			}
			set
			{
				if ((this._HCKeywordTypeCode != value))
				{
					this.OnHCKeywordTypeCodeChanging(value);
					this.SendPropertyChanging();
					this._HCKeywordTypeCode = value;
					this.SendPropertyChanged("HCKeywordTypeCode");
					this.OnHCKeywordTypeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasPic", DbType="Bit")]
		public System.Nullable<bool> HasPic
		{
			get
			{
				return this._HasPic;
			}
			set
			{
				if ((this._HasPic != value))
				{
					this.OnHasPicChanging(value);
					this.SendPropertyChanging();
					this._HasPic = value;
					this.SendPropertyChanged("HasPic");
					this.OnHasPicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImgUrl", DbType="NVarChar(500)")]
		public string ImgUrl
		{
			get
			{
				return this._ImgUrl;
			}
			set
			{
				if ((this._ImgUrl != value))
				{
					this.OnImgUrlChanging(value);
					this.SendPropertyChanging();
					this._ImgUrl = value;
					this.SendPropertyChanged("ImgUrl");
					this.OnImgUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="NVarChar(4000)")]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this.OnRoleChanging(value);
					this.SendPropertyChanging();
					this._Role = value;
					this.SendPropertyChanged("Role");
					this.OnRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImgPath", DbType="NVarChar(50)")]
		public string ImgPath
		{
			get
			{
				return this._ImgPath;
			}
			set
			{
				if ((this._ImgPath != value))
				{
					this.OnImgPathChanging(value);
					this.SendPropertyChanging();
					this._ImgPath = value;
					this.SendPropertyChanged("ImgPath");
					this.OnImgPathChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
