<?xml version="1.0" encoding="utf-8"?><Database Name="RoboNewserDB" Class="NewsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=RoboNewserDB;Persist Security Info=True;User ID=sa;MultipleActiveResultSets=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RoboNewserConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.News" Member="News">
    <Type Name="News">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="HCResourceSiteCatCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HCPriorityCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NewsDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Source" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Urgent" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="PicName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Contents" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Url" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ImgUrl" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="HCLevelCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResouceSiteCatCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HCGatherTypeCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Rate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShowInFirstPage" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LanguageCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ConvertedContent" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ViewCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ZoneCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="News_NewsNewsFlows" Member="NewsNewsFlows" ThisKey="Code" OtherKey="NewsCode" Type="NewsNewsFlows" />
    </Type>
  </Table>
  <Table Name="dbo.vRandNews" Member="vRandNews">
    <Type Name="vRandNew">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="ResourceSite" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vRandPicNews" Member="vRandPicNews">
    <Type Name="vRandPicNews">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="ResourceName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PicName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Contents" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NewsDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ResourceSiteCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ResourceSiteCatCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vLatestNews" Member="vLatestNews">
    <Type Name="vLatestNews">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="ResourceName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PicName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Contents" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NewsDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ResourceSiteCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ResourceSiteCatCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CatCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImgUrl" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vRandTextNews" Member="vRandTextNews">
    <Type Name="vRandTextNews">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="NewsDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vNewsByCatCode" Member="vNewsByCatCodes">
    <Type Name="vNewsByCatCode">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="PicName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Contents" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CatCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResourceName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NewsDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ResourceSiteCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vNewsByKeywords" Member="vNewsByKeywords">
    <Type Name="vNewsByKeywords">
      <Column Name="Title" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="NewsDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PicName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Contents" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Keyword" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KeywordCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ResourceName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ResourceSiteCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vNewsflowNews" Member="vNewsflowNews">
    <Type Name="vNewsflowNews">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NewsFlowCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="Contents" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NewsDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PicName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ResourceName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ResourceSiteCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vImportantKeywords" Member="vImportantKeywords">
    <Type Name="vImportantKeywords">
      <Column Name="Keyword" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="KeywordCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KeywordCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.NewsVisits" Member="NewsVisits">
    <Type Name="NewsVisits">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NewsCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VisitDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vMostVisitedNews" Member="vMostVisitedNews">
    <Type Name="vMostVisitedNews">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="NewsDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VisitCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vMVNews12h" Member="vMVNews12hs">
    <Type Name="vMVNews12h">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="NewsDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VisitCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vMVNews24h" Member="vMVNews24hs">
    <Type Name="vMVNews24h">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="NewsDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VisitCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vMVNews4h" Member="vMVNews4hs">
    <Type Name="vMVNews4h">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="NewsDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VisitCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NewsEmails" Member="NewsEmails">
    <Type Name="NewsEmails">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SenderIP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NewsFlowsKeywords" Member="NewsFlowsKeywords">
    <Type Name="NewsFlowsKeywords">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NewsFlowCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KeywordCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NewsFlows_NewsFlowsKeywords" Member="NewsFlows" ThisKey="NewsFlowCode" OtherKey="Code" Type="NewsFlows" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NewsNewsFlows" Member="NewsNewsFlows">
    <Type Name="NewsNewsFlows">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NewsCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NewsFlowCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="News_NewsNewsFlows" Member="News" ThisKey="NewsCode" OtherKey="Code" Type="News" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="NewsFlows_NewsNewsFlows" Member="NewsFlows" ThisKey="NewsFlowCode" OtherKey="Code" Type="NewsFlows" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.vNewsFlows" Member="vNewsFlows">
    <Type Name="vNewsFlows">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="EDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vNewsFlowsKeywords" Member="vNewsFlowsKeywords">
    <Type Name="vNewsFlowsKeywords">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NewsFlowCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vNewsNewsFlows" Member="vNewsNewsFlows">
    <Type Name="vNewsNewsFlows">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NewsCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vNewsDetail" Member="vNewsDetails">
    <Type Name="vNewsDetail">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="NewsDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Contents" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PicName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CatCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ViewCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ResouceSiteCatCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResouseSiteCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CatName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ImgUrl" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NewsFlows" Member="NewsFlows">
    <Type Name="NewsFlows">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PicName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ShowOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HCShowTypeCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="NewsFlows_NewsFlowsKeywords" Member="NewsFlowsKeywords" ThisKey="Code" OtherKey="NewsFlowCode" Type="NewsFlowsKeywords" />
      <Association Name="NewsFlows_NewsNewsFlows" Member="NewsNewsFlows" ThisKey="Code" OtherKey="NewsFlowCode" Type="NewsNewsFlows" />
    </Type>
  </Table>
  <Table Name="dbo.vNews" Member="vNews">
    <Type Name="vNews">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NewsCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="NDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ResourceSite" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CatName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CatCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResouseSiteCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImgUrl" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="NewsDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HCResourceSiteCatCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Contents" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PicName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vHeadlineNews" Member="vHeadlineNews">
    <Type Name="vHeadlineNews">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NewsCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="NDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ResourceSite" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CatName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CatCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResouseSiteCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImgUrl" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="NewsDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HCResourceSiteCatCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Contents" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PicName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="RelNewsCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vLatestPicNews" Member="vLatestPicNews">
    <Type Name="vLatestPicNews">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="ResourceName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PicName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Contents" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ImgUrl" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ResouseSiteCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CatCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="imgWidth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="imgHeight" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vTinyNews" Member="vTinyNews">
    <Type Name="vTinyNews">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="ImgUrl" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="PicName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ResourceSite" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vRelatedNews" Member="vRelatedNews">
    <Type Name="vRelatedNews">
      <Column Name="EntityCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="HCEntityTypeCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RelatedCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ResourceName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CatName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PicName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="NewsDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Contents" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ResourceSiteCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImgUrl" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="NDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NTime" Type="System.String" DbType="Char(5)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NewsImages" Member="NewsImages">
    <Type Name="NewsImages">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NewsCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ImgUrl" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vTinyLatestNews" Member="vTinyLatestNews">
    <Type Name="vTinyLatestNews">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="ResourceName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NewsDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ResourceSiteCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ResourceSiteCatCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CatCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.spGetRelatedNewsFlows" Method="spGetRelatedNewsFlows">
    <Parameter Name="NewsCode" Parameter="newsCode" Type="System.Int32" DbType="Int" />
    <ElementType Name="spGetRelatedNewsFlowsResult">
      <Column Name="NewsFlowCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KeyCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spReportNewsStatistics" Method="spReportNewsStatistics">
    <Parameter Name="RepType" Parameter="repType" Type="System.Int32" DbType="Int" />
    <Parameter Name="StartNewsDate" Parameter="startNewsDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="EndNewsDate" Parameter="endNewsDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Source" Parameter="source" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="CountryCode" Parameter="countryCode" Type="System.Int32" DbType="Int" />
    <Parameter Name="LanguageCode" Parameter="languageCode" Type="System.Int32" DbType="Int" />
    <Parameter Name="HCResourceSiteCatCode" Parameter="hCResourceSiteCatCode" Type="System.Int32" DbType="Int" />
    <Parameter Name="HCLevelCode" Parameter="hCLevelCode" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spInsertNews" Method="spInsertNews">
    <Parameter Name="SiteCode" Parameter="siteCode" Type="System.Int32" DbType="Int" />
    <Parameter Name="HCResourceSiteCatCode" Parameter="hCResourceSiteCatCode" Type="System.Int32" DbType="Int" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="Url" Parameter="url" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="NewsDate" Parameter="newsDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Contents" Parameter="contents" Type="System.String" DbType="NText" />
    <Parameter Name="ImgUrl" Parameter="imgUrl" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="PicName" Parameter="picName" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="LanguageCode" Parameter="languageCode" Type="System.Int32" DbType="Int" />
    <Parameter Name="NewsCode" Parameter="newsCode" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spGetRelatedPicNews" Method="spGetRelatedPicNews">
    <Parameter Name="NewsCode" Parameter="newsCode" Type="System.Int32" DbType="Int" />
    <ElementType Name="spGetRelatedPicNewsResult">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PicName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spGetNewsAdvertises" Method="spGetNewsAdvertises">
    <Parameter Name="NewsCode" Parameter="newsCode" Type="System.Int32" DbType="Int" />
    <ElementType Name="spGetNewsAdvertisesResult">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ExpDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Rate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HCAdvertiseStatusCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HCStateCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SmallPicFile" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="UserCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="HCAdvertiseCatCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ShamsiCreateDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MasterCatCode" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spUpdateNewsviewCount" Method="spUpdateNewsviewCount">
    <Parameter Name="Code" Parameter="code" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spGetNewsByKeywordCode" Method="spGetNewsByKeywordCode">
    <Parameter Name="KeywordCode" Parameter="keywordCode" Type="System.Int32" DbType="Int" />
    <ElementType Name="spGetNewsByKeywordCodeResult">
      <Column Name="Title" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="NewsDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PicName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Contents" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Keyword" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KeywordCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ResourceName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ResourceSiteCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.fnGetNewsVisitCount" Method="fnGetNewsVisitCount" IsComposable="true">
    <Parameter Name="NewsCode" Parameter="newsCode" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spSearchNewsCount" Method="spSearchNewsCount">
    <Parameter Name="WhereClause" Parameter="whereClause" Type="System.String" DbType="NVarChar(1000)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spDeleteNews" Method="spDeleteNews">
    <Parameter Name="NewsCode" Parameter="newsCode" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spGetPicNewsByKeywordCode" Method="spGetPicNewsByKeywordCode">
    <Parameter Name="KeywordCode" Parameter="keywordCode" Type="System.Int32" DbType="Int" />
    <ElementType Name="spGetPicNewsByKeywordCodeResult">
      <Column Name="Title" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="NewsDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PicName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ImgUrl" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Keyword" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KeywordCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ResourceName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ResouseSiteCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>