#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoboNewser.Code.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RoboNewser")]
	public partial class ResourceSitesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertResourseSiteCats(ResourseSiteCats instance);
    partial void UpdateResourseSiteCats(ResourseSiteCats instance);
    partial void DeleteResourseSiteCats(ResourseSiteCats instance);
    partial void InsertResourceSites(ResourceSites instance);
    partial void UpdateResourceSites(ResourceSites instance);
    partial void DeleteResourceSites(ResourceSites instance);
    #endregion
		
		public ResourceSitesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["RoboNewserConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ResourceSitesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ResourceSitesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ResourceSitesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ResourceSitesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<vResourceSites> vResourceSites
		{
			get
			{
				return this.GetTable<vResourceSites>();
			}
		}
		
		public System.Data.Linq.Table<vRandDataResources> vRandDataResources
		{
			get
			{
				return this.GetTable<vRandDataResources>();
			}
		}
		
		public System.Data.Linq.Table<ResourseSiteCats> ResourseSiteCats
		{
			get
			{
				return this.GetTable<ResourseSiteCats>();
			}
		}
		
		public System.Data.Linq.Table<vActiveResourceSites> vActiveResourceSites
		{
			get
			{
				return this.GetTable<vActiveResourceSites>();
			}
		}
		
		public System.Data.Linq.Table<ResourceSites> ResourceSites
		{
			get
			{
				return this.GetTable<ResourceSites>();
			}
		}
		
		public System.Data.Linq.Table<vResourseSiteCats> vResourseSiteCats
		{
			get
			{
				return this.GetTable<vResourseSiteCats>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vResourceSites")]
	public partial class vResourceSites
	{
		
		private int _Code;
		
		private string _Name;
		
		private System.Nullable<bool> _Active;
		
		private string _LangName;
		
		private string _Entity;
		
		public vResourceSites()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(500)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LangName", DbType="NVarChar(500)")]
		public string LangName
		{
			get
			{
				return this._LangName;
			}
			set
			{
				if ((this._LangName != value))
				{
					this._LangName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entity", DbType="NVarChar(1000)")]
		public string Entity
		{
			get
			{
				return this._Entity;
			}
			set
			{
				if ((this._Entity != value))
				{
					this._Entity = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vRandDataResources")]
	public partial class vRandDataResources
	{
		
		private int _Code;
		
		private string _Name;
		
		public vRandDataResources()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(500)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ResourseSiteCats")]
	public partial class ResourseSiteCats : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private System.Nullable<int> _ResouseSiteCode;
		
		private string _Url;
		
		private System.Nullable<int> _CatCode;
		
		private System.Nullable<bool> _Active;
		
		private string _RssUrl;
		
		private bool _RssIsActive;
		
		private EntityRef<ResourceSites> _ResourceSites;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnResouseSiteCodeChanging(System.Nullable<int> value);
    partial void OnResouseSiteCodeChanged();
    partial void OnUrlChanging(string value);
    partial void OnUrlChanged();
    partial void OnCatCodeChanging(System.Nullable<int> value);
    partial void OnCatCodeChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    partial void OnRssUrlChanging(string value);
    partial void OnRssUrlChanged();
    partial void OnRssIsActiveChanging(bool value);
    partial void OnRssIsActiveChanged();
    #endregion
		
		public ResourseSiteCats()
		{
			this._ResourceSites = default(EntityRef<ResourceSites>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResouseSiteCode", DbType="Int")]
		public System.Nullable<int> ResouseSiteCode
		{
			get
			{
				return this._ResouseSiteCode;
			}
			set
			{
				if ((this._ResouseSiteCode != value))
				{
					if (this._ResourceSites.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnResouseSiteCodeChanging(value);
					this.SendPropertyChanging();
					this._ResouseSiteCode = value;
					this.SendPropertyChanged("ResouseSiteCode");
					this.OnResouseSiteCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="VarChar(500)")]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this.OnUrlChanging(value);
					this.SendPropertyChanging();
					this._Url = value;
					this.SendPropertyChanged("Url");
					this.OnUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatCode", DbType="Int")]
		public System.Nullable<int> CatCode
		{
			get
			{
				return this._CatCode;
			}
			set
			{
				if ((this._CatCode != value))
				{
					this.OnCatCodeChanging(value);
					this.SendPropertyChanging();
					this._CatCode = value;
					this.SendPropertyChanged("CatCode");
					this.OnCatCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RssUrl", DbType="NVarChar(500)")]
		public string RssUrl
		{
			get
			{
				return this._RssUrl;
			}
			set
			{
				if ((this._RssUrl != value))
				{
					this.OnRssUrlChanging(value);
					this.SendPropertyChanging();
					this._RssUrl = value;
					this.SendPropertyChanged("RssUrl");
					this.OnRssUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RssIsActive", DbType="Bit NOT NULL")]
		public bool RssIsActive
		{
			get
			{
				return this._RssIsActive;
			}
			set
			{
				if ((this._RssIsActive != value))
				{
					this.OnRssIsActiveChanging(value);
					this.SendPropertyChanging();
					this._RssIsActive = value;
					this.SendPropertyChanged("RssIsActive");
					this.OnRssIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ResourceSites_ResourseSiteCats", Storage="_ResourceSites", ThisKey="ResouseSiteCode", OtherKey="Code", IsForeignKey=true)]
		public ResourceSites ResourceSites
		{
			get
			{
				return this._ResourceSites.Entity;
			}
			set
			{
				ResourceSites previousValue = this._ResourceSites.Entity;
				if (((previousValue != value) 
							|| (this._ResourceSites.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ResourceSites.Entity = null;
						previousValue.ResourseSiteCats.Remove(this);
					}
					this._ResourceSites.Entity = value;
					if ((value != null))
					{
						value.ResourseSiteCats.Add(this);
						this._ResouseSiteCode = value.Code;
					}
					else
					{
						this._ResouseSiteCode = default(Nullable<int>);
					}
					this.SendPropertyChanged("ResourceSites");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vActiveResourceSites")]
	public partial class vActiveResourceSites
	{
		
		private int _Code;
		
		private string _Name;
		
		private System.Nullable<bool> _Active;
		
		public vActiveResourceSites()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(500)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ResourceSites")]
	public partial class ResourceSites : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private string _Name;
		
		private System.Nullable<bool> _Active;
		
		private System.Nullable<bool> _BaseSite;
		
		private string _RELink;
		
		private string _REDetail;
		
		private string _REImage;
		
		private string _REVideo;
		
		private string _LinkDomainName;
		
		private System.Nullable<int> _HCEncodingTypeCode;
		
		private System.Nullable<int> _LanguageCode;
		
		private int _HCEntityTypeCode;
		
		private System.Nullable<int> _ZoneCode;
		
		private string _BaseURL;
		
		private string _LogoUrl;
		
		private EntitySet<ResourseSiteCats> _ResourseSiteCats;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    partial void OnBaseSiteChanging(System.Nullable<bool> value);
    partial void OnBaseSiteChanged();
    partial void OnRELinkChanging(string value);
    partial void OnRELinkChanged();
    partial void OnREDetailChanging(string value);
    partial void OnREDetailChanged();
    partial void OnREImageChanging(string value);
    partial void OnREImageChanged();
    partial void OnREVideoChanging(string value);
    partial void OnREVideoChanged();
    partial void OnLinkDomainNameChanging(string value);
    partial void OnLinkDomainNameChanged();
    partial void OnHCEncodingTypeCodeChanging(System.Nullable<int> value);
    partial void OnHCEncodingTypeCodeChanged();
    partial void OnLanguageCodeChanging(System.Nullable<int> value);
    partial void OnLanguageCodeChanged();
    partial void OnHCEntityTypeCodeChanging(int value);
    partial void OnHCEntityTypeCodeChanged();
    partial void OnZoneCodeChanging(System.Nullable<int> value);
    partial void OnZoneCodeChanged();
    partial void OnBaseURLChanging(string value);
    partial void OnBaseURLChanged();
    partial void OnLogoUrlChanging(string value);
    partial void OnLogoUrlChanged();
    #endregion
		
		public ResourceSites()
		{
			this._ResourseSiteCats = new EntitySet<ResourseSiteCats>(new Action<ResourseSiteCats>(this.attach_ResourseSiteCats), new Action<ResourseSiteCats>(this.detach_ResourseSiteCats));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(500)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseSite", DbType="Bit")]
		public System.Nullable<bool> BaseSite
		{
			get
			{
				return this._BaseSite;
			}
			set
			{
				if ((this._BaseSite != value))
				{
					this.OnBaseSiteChanging(value);
					this.SendPropertyChanging();
					this._BaseSite = value;
					this.SendPropertyChanged("BaseSite");
					this.OnBaseSiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RELink", DbType="NVarChar(500)")]
		public string RELink
		{
			get
			{
				return this._RELink;
			}
			set
			{
				if ((this._RELink != value))
				{
					this.OnRELinkChanging(value);
					this.SendPropertyChanging();
					this._RELink = value;
					this.SendPropertyChanged("RELink");
					this.OnRELinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REDetail", DbType="NVarChar(500)")]
		public string REDetail
		{
			get
			{
				return this._REDetail;
			}
			set
			{
				if ((this._REDetail != value))
				{
					this.OnREDetailChanging(value);
					this.SendPropertyChanging();
					this._REDetail = value;
					this.SendPropertyChanged("REDetail");
					this.OnREDetailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REImage", DbType="NVarChar(500)")]
		public string REImage
		{
			get
			{
				return this._REImage;
			}
			set
			{
				if ((this._REImage != value))
				{
					this.OnREImageChanging(value);
					this.SendPropertyChanging();
					this._REImage = value;
					this.SendPropertyChanged("REImage");
					this.OnREImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REVideo", DbType="NVarChar(500)")]
		public string REVideo
		{
			get
			{
				return this._REVideo;
			}
			set
			{
				if ((this._REVideo != value))
				{
					this.OnREVideoChanging(value);
					this.SendPropertyChanging();
					this._REVideo = value;
					this.SendPropertyChanged("REVideo");
					this.OnREVideoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkDomainName", DbType="NVarChar(100)")]
		public string LinkDomainName
		{
			get
			{
				return this._LinkDomainName;
			}
			set
			{
				if ((this._LinkDomainName != value))
				{
					this.OnLinkDomainNameChanging(value);
					this.SendPropertyChanging();
					this._LinkDomainName = value;
					this.SendPropertyChanged("LinkDomainName");
					this.OnLinkDomainNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCEncodingTypeCode", DbType="Int")]
		public System.Nullable<int> HCEncodingTypeCode
		{
			get
			{
				return this._HCEncodingTypeCode;
			}
			set
			{
				if ((this._HCEncodingTypeCode != value))
				{
					this.OnHCEncodingTypeCodeChanging(value);
					this.SendPropertyChanging();
					this._HCEncodingTypeCode = value;
					this.SendPropertyChanged("HCEncodingTypeCode");
					this.OnHCEncodingTypeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageCode", DbType="Int")]
		public System.Nullable<int> LanguageCode
		{
			get
			{
				return this._LanguageCode;
			}
			set
			{
				if ((this._LanguageCode != value))
				{
					this.OnLanguageCodeChanging(value);
					this.SendPropertyChanging();
					this._LanguageCode = value;
					this.SendPropertyChanged("LanguageCode");
					this.OnLanguageCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCEntityTypeCode", DbType="Int NOT NULL")]
		public int HCEntityTypeCode
		{
			get
			{
				return this._HCEntityTypeCode;
			}
			set
			{
				if ((this._HCEntityTypeCode != value))
				{
					this.OnHCEntityTypeCodeChanging(value);
					this.SendPropertyChanging();
					this._HCEntityTypeCode = value;
					this.SendPropertyChanged("HCEntityTypeCode");
					this.OnHCEntityTypeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZoneCode", DbType="Int")]
		public System.Nullable<int> ZoneCode
		{
			get
			{
				return this._ZoneCode;
			}
			set
			{
				if ((this._ZoneCode != value))
				{
					this.OnZoneCodeChanging(value);
					this.SendPropertyChanging();
					this._ZoneCode = value;
					this.SendPropertyChanged("ZoneCode");
					this.OnZoneCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseURL", DbType="VarChar(500)")]
		public string BaseURL
		{
			get
			{
				return this._BaseURL;
			}
			set
			{
				if ((this._BaseURL != value))
				{
					this.OnBaseURLChanging(value);
					this.SendPropertyChanging();
					this._BaseURL = value;
					this.SendPropertyChanged("BaseURL");
					this.OnBaseURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogoUrl", DbType="NVarChar(200)")]
		public string LogoUrl
		{
			get
			{
				return this._LogoUrl;
			}
			set
			{
				if ((this._LogoUrl != value))
				{
					this.OnLogoUrlChanging(value);
					this.SendPropertyChanging();
					this._LogoUrl = value;
					this.SendPropertyChanged("LogoUrl");
					this.OnLogoUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ResourceSites_ResourseSiteCats", Storage="_ResourseSiteCats", ThisKey="Code", OtherKey="ResouseSiteCode")]
		public EntitySet<ResourseSiteCats> ResourseSiteCats
		{
			get
			{
				return this._ResourseSiteCats;
			}
			set
			{
				this._ResourseSiteCats.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ResourseSiteCats(ResourseSiteCats entity)
		{
			this.SendPropertyChanging();
			entity.ResourceSites = this;
		}
		
		private void detach_ResourseSiteCats(ResourseSiteCats entity)
		{
			this.SendPropertyChanging();
			entity.ResourceSites = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vResourseSiteCats")]
	public partial class vResourseSiteCats
	{
		
		private int _Code;
		
		private System.Nullable<int> _ResouseSiteCode;
		
		private string _Name;
		
		private string _CatName;
		
		private System.Nullable<bool> _ActiveCat;
		
		private System.Nullable<bool> _Active;
		
		private System.Nullable<bool> _BaseSite;
		
		private string _RELink;
		
		private string _REDetail;
		
		private string _REImage;
		
		private string _LinkDomainName;
		
		private System.Nullable<int> _HCEncodingTypeCode;
		
		private System.Nullable<int> _LanguageCode;
		
		private int _HCEntityTypeCode;
		
		private System.Nullable<int> _ZoneCode;
		
		private string _BaseURL;
		
		private System.Nullable<int> _CatCode;
		
		private string _Url;
		
		private string _RssUrl;
		
		private System.Nullable<bool> _RssIsActive;
		
		private string _REVideo;
		
		public vResourseSiteCats()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResouseSiteCode", DbType="Int")]
		public System.Nullable<int> ResouseSiteCode
		{
			get
			{
				return this._ResouseSiteCode;
			}
			set
			{
				if ((this._ResouseSiteCode != value))
				{
					this._ResouseSiteCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(500)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatName", DbType="NVarChar(500)")]
		public string CatName
		{
			get
			{
				return this._CatName;
			}
			set
			{
				if ((this._CatName != value))
				{
					this._CatName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActiveCat", DbType="Bit")]
		public System.Nullable<bool> ActiveCat
		{
			get
			{
				return this._ActiveCat;
			}
			set
			{
				if ((this._ActiveCat != value))
				{
					this._ActiveCat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseSite", DbType="Bit")]
		public System.Nullable<bool> BaseSite
		{
			get
			{
				return this._BaseSite;
			}
			set
			{
				if ((this._BaseSite != value))
				{
					this._BaseSite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RELink", DbType="NVarChar(500)")]
		public string RELink
		{
			get
			{
				return this._RELink;
			}
			set
			{
				if ((this._RELink != value))
				{
					this._RELink = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REDetail", DbType="NVarChar(500)")]
		public string REDetail
		{
			get
			{
				return this._REDetail;
			}
			set
			{
				if ((this._REDetail != value))
				{
					this._REDetail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REImage", DbType="NVarChar(500)")]
		public string REImage
		{
			get
			{
				return this._REImage;
			}
			set
			{
				if ((this._REImage != value))
				{
					this._REImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkDomainName", DbType="NVarChar(100)")]
		public string LinkDomainName
		{
			get
			{
				return this._LinkDomainName;
			}
			set
			{
				if ((this._LinkDomainName != value))
				{
					this._LinkDomainName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCEncodingTypeCode", DbType="Int")]
		public System.Nullable<int> HCEncodingTypeCode
		{
			get
			{
				return this._HCEncodingTypeCode;
			}
			set
			{
				if ((this._HCEncodingTypeCode != value))
				{
					this._HCEncodingTypeCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageCode", DbType="Int")]
		public System.Nullable<int> LanguageCode
		{
			get
			{
				return this._LanguageCode;
			}
			set
			{
				if ((this._LanguageCode != value))
				{
					this._LanguageCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCEntityTypeCode", DbType="Int NOT NULL")]
		public int HCEntityTypeCode
		{
			get
			{
				return this._HCEntityTypeCode;
			}
			set
			{
				if ((this._HCEntityTypeCode != value))
				{
					this._HCEntityTypeCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZoneCode", DbType="Int")]
		public System.Nullable<int> ZoneCode
		{
			get
			{
				return this._ZoneCode;
			}
			set
			{
				if ((this._ZoneCode != value))
				{
					this._ZoneCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseURL", DbType="VarChar(500)")]
		public string BaseURL
		{
			get
			{
				return this._BaseURL;
			}
			set
			{
				if ((this._BaseURL != value))
				{
					this._BaseURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatCode", DbType="Int")]
		public System.Nullable<int> CatCode
		{
			get
			{
				return this._CatCode;
			}
			set
			{
				if ((this._CatCode != value))
				{
					this._CatCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="VarChar(500)")]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this._Url = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RssUrl", DbType="NVarChar(500)")]
		public string RssUrl
		{
			get
			{
				return this._RssUrl;
			}
			set
			{
				if ((this._RssUrl != value))
				{
					this._RssUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RssIsActive", DbType="Bit")]
		public System.Nullable<bool> RssIsActive
		{
			get
			{
				return this._RssIsActive;
			}
			set
			{
				if ((this._RssIsActive != value))
				{
					this._RssIsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REVideo", DbType="NVarChar(500)")]
		public string REVideo
		{
			get
			{
				return this._REVideo;
			}
			set
			{
				if ((this._REVideo != value))
				{
					this._REVideo = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
