<?xml version="1.0" encoding="utf-8"?><Database Name="RoboNewser" Class="SitesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=RoboNewser;Persist Security Info=True;User ID=sa;MultipleActiveResultSets=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RoboNewserConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SiteCatNames" Member="SiteCatNames">
    <Type Name="SiteCatNames">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Parent" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AllSites" Member="AllSites">
    <Type Name="AllSites">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="SiteName" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Cat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Source" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VisitCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Rating" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ViewerCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SumAll" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Active" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SenderName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SenderEmail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>